Target-seeking added
SorenWi/Boid_Addon_Blender pull request #31
Opened 2023-01-15 16:09 UTC by Yannick-Kraus

Add Target-seeking and SetupTarget-Operator

2023-01-15 21:33 UTC, KakuschkeFelix requested changes
Bitte allgemein auch nochmal pylint (gibt es als VS Code Addon) drüber laufen lassen und notfalls Fehler fixen

2023-01-15 21:33 UTC, KakuschkeFelix commented on BoidAddon.py
> +    target = (0, 0, 0)
Ich würde `target` nur unten bei update mitgeben, damit nicht alle Boids das target speichern müssen

2023-01-15 21:33 UTC, KakuschkeFelix commented on BoidAddon.py
> +        Boid.target = instance[0].location
Die Methode könnte dann weg

2023-01-15 21:33 UTC, KakuschkeFelix commented on BoidAddon.py
> +        direction_vec = subtract_tuples(tuple(Boid.target), tuple(self.instance.location))
`target_location` käme aus update()

2023-01-15 21:33 UTC, KakuschkeFelix commented on BoidAddon.py
> +        super().__init__(Boid.save_target)
Das stattdessen als property von `BoidDataCore` speichern

2023-01-18 14:39 UTC, SorenWi approved these changes

2023-01-18 14:40 UTC, merged